sudo: required
services:
  - docker
language: generic 

before_install:
  - docker build -t wacharin-stack/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wacharin-stack/react-test npm test

after_success:
  - docker build -t wacharin-stack/multi-client ./client
  - docker build -t wacharin-stack/multi-nginx ./nginx
  - docker build -t wacharin-stack/multi-server ./server
  - docker build -t wacharin-stack/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push wacharin-stack/multi-client
  - docker push wacharin-stack/multi-nginx
  - docker push wacharin-stack/multi-server
  - docker push wacharin-stack/multi-worker